//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 10:02:27 AM IST 
//


package com.sap.csc.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sap.csc.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ApiResponseError_QNAME = new QName("", "apiResponseError");
    private final static QName _Request_QNAME = new QName("", "request");
    private final static QName _Appendix_QNAME = new QName("", "appendix");
    private final static QName _Response_QNAME = new QName("", "response");
    private final static QName _AlertCapabilities_QNAME = new QName("", "alertCapabilities");
    private final static QName _Airline_QNAME = new QName("", "airline");
    private final static QName _Airport_QNAME = new QName("", "airport");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sap.csc.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AlertRuleV1 }
     * 
     */
    public AlertRuleV1 createAlertRuleV1() {
        return new AlertRuleV1();
    }

    /**
     * Create an instance of {@link Appendices }
     * 
     */
    public Appendices createAppendices() {
        return new Appendices();
    }

    /**
     * Create an instance of {@link ApiResponseError }
     * 
     */
    public ApiResponseError createApiResponseError() {
        return new ApiResponseError();
    }

    /**
     * Create an instance of {@link AlertCapabilities }
     * 
     */
    public AlertCapabilities createAlertCapabilities() {
        return new AlertCapabilities();
    }

    /**
     * Create an instance of {@link AirlineV1 }
     * 
     */
    public AirlineV1 createAirlineV1() {
        return new AirlineV1();
    }

    /**
     * Create an instance of {@link AirportV1 }
     * 
     */
    public AirportV1 createAirportV1() {
        return new AirportV1();
    }

    /**
     * Create an instance of {@link RequestBase }
     * 
     */
    public RequestBase createRequestBase() {
        return new RequestBase();
    }

    /**
     * Create an instance of {@link RequestedAirportV1 }
     * 
     */
    public RequestedAirportV1 createRequestedAirportV1() {
        return new RequestedAirportV1();
    }

    /**
     * Create an instance of {@link RequestedEnum }
     * 
     */
    public RequestedEnum createRequestedEnum() {
        return new RequestedEnum();
    }

    /**
     * Create an instance of {@link RequestedString }
     * 
     */
    public RequestedString createRequestedString() {
        return new RequestedString();
    }

    /**
     * Create an instance of {@link RequestRoute }
     * 
     */
    public RequestRoute createRequestRoute() {
        return new RequestRoute();
    }

    /**
     * Create an instance of {@link ResponseRoute }
     * 
     */
    public ResponseRoute createResponseRoute() {
        return new ResponseRoute();
    }

    /**
     * Create an instance of {@link ResponseFlight }
     * 
     */
    public ResponseFlight createResponseFlight() {
        return new ResponseFlight();
    }

    /**
     * Create an instance of {@link RuleEventV1 }
     * 
     */
    public RuleEventV1 createRuleEventV1() {
        return new RuleEventV1();
    }

    /**
     * Create an instance of {@link ResponseRule }
     * 
     */
    public ResponseRule createResponseRule() {
        return new ResponseRule();
    }

    /**
     * Create an instance of {@link RequestRuleById }
     * 
     */
    public RequestRuleById createRequestRuleById() {
        return new RequestRuleById();
    }

    /**
     * Create an instance of {@link NameValueV1 }
     * 
     */
    public NameValueV1 createNameValueV1() {
        return new NameValueV1();
    }

    /**
     * Create an instance of {@link ResponseRuleById }
     * 
     */
    public ResponseRuleById createResponseRuleById() {
        return new ResponseRuleById();
    }

    /**
     * Create an instance of {@link AlertDeliveryV1 }
     * 
     */
    public AlertDeliveryV1 createAlertDeliveryV1() {
        return new AlertDeliveryV1();
    }

    /**
     * Create an instance of {@link RequestedDate }
     * 
     */
    public RequestedDate createRequestedDate() {
        return new RequestedDate();
    }

    /**
     * Create an instance of {@link RequestFlight }
     * 
     */
    public RequestFlight createRequestFlight() {
        return new RequestFlight();
    }

    /**
     * Create an instance of {@link RequestedAirlineV1 }
     * 
     */
    public RequestedAirlineV1 createRequestedAirlineV1() {
        return new RequestedAirlineV1();
    }

    /**
     * Create an instance of {@link AlertRuleV1 .RuleEvents }
     * 
     */
    public AlertRuleV1 .RuleEvents createAlertRuleV1RuleEvents() {
        return new AlertRuleV1 .RuleEvents();
    }

    /**
     * Create an instance of {@link AlertRuleV1 .NameValues }
     * 
     */
    public AlertRuleV1 .NameValues createAlertRuleV1NameValues() {
        return new AlertRuleV1 .NameValues();
    }

    /**
     * Create an instance of {@link com.sap.csc.domain.RequestRuleCreate.Events }
     * 
     */
    public com.sap.csc.domain.RequestRuleCreate.Events createRequestRuleCreateEvents() {
        return new com.sap.csc.domain.RequestRuleCreate.Events();
    }

    /**
     * Create an instance of {@link com.sap.csc.domain.RequestRuleCreate.NameValues }
     * 
     */
    public com.sap.csc.domain.RequestRuleCreate.NameValues createRequestRuleCreateNameValues() {
        return new com.sap.csc.domain.RequestRuleCreate.NameValues();
    }

    /**
     * Create an instance of {@link Appendices.Airlines }
     * 
     */
    public Appendices.Airlines createAppendicesAirlines() {
        return new Appendices.Airlines();
    }

    /**
     * Create an instance of {@link Appendices.Airports }
     * 
     */
    public Appendices.Airports createAppendicesAirports() {
        return new Appendices.Airports();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApiResponseError }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apiResponseError")
    public JAXBElement<ApiResponseError> createApiResponseError(ApiResponseError value) {
        return new JAXBElement<ApiResponseError>(_ApiResponseError_QNAME, ApiResponseError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "request")
    public JAXBElement<Object> createRequest(Object value) {
        return new JAXBElement<Object>(_Request_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Appendices }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "appendix")
    public JAXBElement<Appendices> createAppendix(Appendices value) {
        return new JAXBElement<Appendices>(_Appendix_QNAME, Appendices.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "response")
    public JAXBElement<Object> createResponse(Object value) {
        return new JAXBElement<Object>(_Response_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AlertCapabilities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "alertCapabilities")
    public JAXBElement<AlertCapabilities> createAlertCapabilities(AlertCapabilities value) {
        return new JAXBElement<AlertCapabilities>(_AlertCapabilities_QNAME, AlertCapabilities.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AirlineV1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "airline")
    public JAXBElement<AirlineV1> createAirline(AirlineV1 value) {
        return new JAXBElement<AirlineV1>(_Airline_QNAME, AirlineV1 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AirportV1 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "airport")
    public JAXBElement<AirportV1> createAirport(AirportV1 value) {
        return new JAXBElement<AirportV1>(_Airport_QNAME, AirportV1 .class, null, value);
    }

}
