//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 10:02:27 AM IST 
//


package com.sap.csc.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for responseRule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responseRule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rule" type="{}alertRuleV1" minOccurs="0"/>
 *         &lt;element name="error" type="{}apiResponseError" minOccurs="0"/>
 *         &lt;element ref="{}appendix" minOccurs="0"/>
 *         &lt;element ref="{}alertCapabilities" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responseRule", propOrder = {
    "rule",
    "error",
    "appendix",
    "alertCapabilities"
})
@XmlSeeAlso({
    ResponseRoute.class,
    ResponseFlight.class,
    ResponseRuleById.class
})
public class ResponseRule {

    protected AlertRuleV1 rule;
    protected ApiResponseError error;
    protected Appendices appendix;
    protected AlertCapabilities alertCapabilities;

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link AlertRuleV1 }
     *     
     */
    public AlertRuleV1 getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertRuleV1 }
     *     
     */
    public void setRule(AlertRuleV1 value) {
        this.rule = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ApiResponseError }
     *     
     */
    public ApiResponseError getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApiResponseError }
     *     
     */
    public void setError(ApiResponseError value) {
        this.error = value;
    }

    /**
     * Gets the value of the appendix property.
     * 
     * @return
     *     possible object is
     *     {@link Appendices }
     *     
     */
    public Appendices getAppendix() {
        return appendix;
    }

    /**
     * Sets the value of the appendix property.
     * 
     * @param value
     *     allowed object is
     *     {@link Appendices }
     *     
     */
    public void setAppendix(Appendices value) {
        this.appendix = value;
    }

    /**
     * Gets the value of the alertCapabilities property.
     * 
     * @return
     *     possible object is
     *     {@link AlertCapabilities }
     *     
     */
    public AlertCapabilities getAlertCapabilities() {
        return alertCapabilities;
    }

    /**
     * Sets the value of the alertCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertCapabilities }
     *     
     */
    public void setAlertCapabilities(AlertCapabilities value) {
        this.alertCapabilities = value;
    }

}
